In [2]:
import pandas as pd
import numpy as np

In [19]:
bacterialData = pd.read_csv("/Users/keerthyrangan/Downloads/bacteria(Sheet1).csv", encoding = "latin-1")
bacterialData

/var/folders/l4/kpydl4ws7zd8nz43jqjhct5r0000gn/T/ipykernel_33797/2602944678.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  bacterialData = pd.read_csv("/Users/keerthyrangan/Downloads/bacteria(Sheet1).csv", encoding = "latin-1")

,EventID,EventDate,GroupID,GroupName,SiteID,SiteName,site_latitude,site_longitude,site_altitude,bact_detail_rid,...,hold_end_datetime,min_temp,max_temp,three_M_plate,ecoli_idexx,fecal_coliform,ecoli_other,ecoli_other_unit,comments,warnings
0,770,3/18/96 12:00 PM,245,Salem High School,141,Snapping Shoals,33.5936,-83.9852,228.927612,1753,...,NaN,NaN,NaN,1,NaN,310.0,NaN,NaN,NaN,NaN
1,763,5/14/96 12:00 PM,245,Salem High School,141,Snapping Shoals,33.5936,-83.9852,228.927612,1751,...,NaN,NaN,NaN,1,NaN,2750.0,NaN,NaN,NaN,NaN
2,653,3/23/98 12:00 PM,208,"Waterford Place Condominium Assoc., Inc.",129,Poplar Creek,33.8976,-84.4759,274.621826,18335,...,NaN,NaN,NaN,1,NaN,-25.0,NaN,NaN,NaN,NaN
3,655,3/24/98 12:00 PM,208,"Waterford Place Condominium Assoc., Inc.",129,Poplar Creek,33.8976,-84.4759,274.621826,17691,...,NaN,NaN,NaN,1,NaN,150.0,NaN,NaN,NaN,NaN
4,657,3/25/98 12:00 PM,208,"Waterford Place Condominium Assoc., Inc.",129,Poplar Creek,33.8976,-84.4759,274.621826,17692,...,NaN,NaN,NaN,1,NaN,50.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46315,99134,12/25/22 4:30 PM,2753,Gram's Collins Gals,5482,Creek between Chimney Springs and Creekstone Way,34.0078,-84.4114,272.980000,49847,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46316,99140,12/26/22 10:25 AM,1906,Satilla Riverkeeper & Friends,7388,Hacklebarney Creek,31.2720,-82.3131,41.700000,49853,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46317,99141,12/26/22 10:55 AM,1906,Satilla Riverkeeper & Friends,3431,Jamestown Landing,31.2983,-82.3924,29.910000,49854,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46318,99135,12/26/22 1:15 PM,3028,SCFP Stream Team,7364,Cambarus Creek,34.1485,-84.0427,339.140000,49848,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46319,99136,12/26/22 4:28 PM,1461,Keep Smyrna Beautiful Adopt-A-Stream (KSBAAS),7363,Poplar Creek,33.8769,-84.4991,296.780000,49849,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
bacterialData["EventDate"] = pd.to_datetime(bacterialData["EventDate"])

bacterialData = bacterialData[bacterialData["EventDate"].dt.year == 2022]
bacterialData

/var/folders/l4/kpydl4ws7zd8nz43jqjhct5r0000gn/T/ipykernel_33797/2943158998.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bacterialData["EventDate"] = pd.to_datetime(bacterialData["EventDate"])

,EventID,EventDate,GroupID,GroupName,SiteID,SiteName,site_latitude,site_longitude,site_altitude,bact_detail_rid,...,hold_end_datetime,min_temp,max_temp,three_M_plate,ecoli_idexx,fecal_coliform,ecoli_other,ecoli_other_unit,comments,warnings
41180,92453,2022-01-01 13:00:00,3017,Birdsong Subdivision,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,275.44000,43565,...,00:00.0,35.0,35.5,0,NaN,NaN,NaN,NaN,NaN,NaN
41181,92446,2022-01-01 16:30:00,1039,Lakewood Colony,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,283.80954,43562,...,30:00.0,34.6,35.8,0,NaN,NaN,NaN,NaN,NaN,NaN
41182,92427,2022-01-03 09:40:00,2875,Lake Sovereign,6866,Lake Sovereign - CHD,34.1628,-84.5329,273.27000,43547,...,30:00.0,35.0,35.0,0,NaN,NaN,NaN,NaN,NaN,NaN
41183,95440,2022-01-03 17:12:00,2994,The Landa Band,7296,Powder Springs Creek at Still Family Farm,33.9042,-84.7194,288.39000,46164,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
41184,98946,2022-01-05 07:30:00,458,Chattahoochee Riverkeeper,6668,Linwood at Linwood Nature Preserve,34.3280,-83.8515,339.18000,48765,...,NaN,NaN,NaN,1,100.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46315,99134,2022-12-25 16:30:00,2753,Gram's Collins Gals,5482,Creek between Chimney Springs and Creekstone Way,34.0078,-84.4114,272.98000,49847,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46316,99140,2022-12-26 10:25:00,1906,Satilla Riverkeeper & Friends,7388,Hacklebarney Creek,31.2720,-82.3131,41.70000,49853,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46317,99141,2022-12-26 10:55:00,1906,Satilla Riverkeeper & Friends,3431,Jamestown Landing,31.2983,-82.3924,29.91000,49854,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46318,99135,2022-12-26 13:15:00,3028,SCFP Stream Team,7364,Cambarus Creek,34.1485,-84.0427,339.14000,49848,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
46319,99136,2022-12-26 16:28:00,1461,Keep Smyrna Beautiful Adopt-A-Stream (KSBAAS),7363,Poplar Creek,33.8769,-84.4991,296.78000,49849,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
bacterialData = bacterialData[bacterialData["min_temp"] > 10]
bacterialData = bacterialData[bacterialData["min_temp"] < 49]
bacterialData = bacterialData[bacterialData["plate_blank"] == 0]

bacterialData

,EventID,EventDate,GroupID,GroupName,SiteID,SiteName,site_latitude,site_longitude,site_altitude,bact_detail_rid,...,hold_end_datetime,min_temp,max_temp,three_M_plate,ecoli_idexx,fecal_coliform,ecoli_other,ecoli_other_unit,comments,warnings
41180,92453,2022-01-01 13:00:00,3017,Birdsong Subdivision,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,275.440000,43565,...,00:00.0,35.0,35.5,0,NaN,NaN,NaN,NaN,NaN,NaN
41181,92446,2022-01-01 16:30:00,1039,Lakewood Colony,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,283.809540,43562,...,30:00.0,34.6,35.8,0,NaN,NaN,NaN,NaN,NaN,NaN
41182,92427,2022-01-03 09:40:00,2875,Lake Sovereign,6866,Lake Sovereign - CHD,34.1628,-84.5329,273.270000,43547,...,30:00.0,35.0,35.0,0,NaN,NaN,NaN,NaN,NaN,NaN
41201,93453,2022-01-05 10:42:00,1087,AAAS Stream Stompers,954,Hollow Creek 2,33.3434,-81.8222,39.512642,44419,...,55:00.0,34.1,34.6,0,NaN,NaN,NaN,NaN,NaN,NaN
41203,93452,2022-01-05 11:11:00,1087,AAAS Stream Stompers,953,Hollow Creek 1,33.3345,-81.8534,35.055412,44418,...,55:00.0,34.1,34.6,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46295,99052,2022-12-19 14:45:00,3014,Christine Brackenrich,7337,Ludie Creek at Simpsonwood Park,33.9827,-84.2436,273.910000,49765,...,15:00.0,34.9,35.2,0,NaN,NaN,NaN,NaN,NaN,NaN
46296,99053,2022-12-19 14:53:00,1501,Friends of Peachtree Hills Park,2033,Peachtree Hills Park,33.8180,-84.3783,256.479279,49766,...,00:00.0,34.5,35.5,0,NaN,NaN,NaN,NaN,NaN,NaN
46298,99116,2022-12-20 10:10:00,1618,Upper Chattahoochee Trout Unlimited,2368,Ball Mill Creek,33.9787,-84.3208,268.422729,49829,...,30:00.0,34.1,35.5,0,NaN,NaN,NaN,NaN,NaN,NaN
46304,99120,2022-12-20 13:30:00,1727,WWALS_Watershed Coalition,6564,Alapaha River at Naylor Park Beach,30.9254,-83.0385,42.410000,49833,...,30:00.0,34.0,35.0,0,NaN,NaN,NaN,NaN,NaN,NaN
46309,99119,2022-12-21 12:10:00,2845,Allatoona Creek Park Survey,6795,Allatoona Creek - Mason Bridge,34.0217,-84.7086,262.180000,49832,...,08:00.0,34.1,35.8,0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
variables_to_keep = ["EventDate","SiteID","SiteName","site_latitude","site_longitude","plate_blank","plate_one",
                     "plate_two","plate_three","colony_avg","min_temp","max_temp"]
bacterialData = bacterialData[variables_to_keep]
bacterialData

,EventDate,SiteID,SiteName,site_latitude,site_longitude,plate_blank,plate_one,plate_two,plate_three,colony_avg,min_temp,max_temp
41180,2022-01-01 13:00:00,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,0.0,11,5,13,966,35.0,35.5
41181,2022-01-01 16:30:00,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,0.0,22,23,19,2133,34.6,35.8
41182,2022-01-03 09:40:00,6866,Lake Sovereign - CHD,34.1628,-84.5329,0.0,24,20,26,2333,35.0,35.0
41201,2022-01-05 10:42:00,954,Hollow Creek 2,33.3434,-81.8222,0.0,2,1,1,133,34.1,34.6
41203,2022-01-05 11:11:00,953,Hollow Creek 1,33.3345,-81.8534,0.0,1,2,0,100,34.1,34.6
...,...,...,...,...,...,...,...,...,...,...,...,...
46295,2022-12-19 14:45:00,7337,Ludie Creek at Simpsonwood Park,33.9827,-84.2436,0.0,1,1,0,66,34.9,35.2
46296,2022-12-19 14:53:00,2033,Peachtree Hills Park,33.8180,-84.3783,0.0,3,2,4,300,34.5,35.5
46298,2022-12-20 10:10:00,2368,Ball Mill Creek,33.9787,-84.3208,0.0,0,1,3,133,34.1,35.5
46304,2022-12-20 13:30:00,6564,Alapaha River at Naylor Park Beach,30.9254,-83.0385,0.0,1,1,1,100,34.0,35.0
46309,2022-12-21 12:10:00,6795,Allatoona Creek - Mason Bridge,34.0217,-84.7086,0.0,1,0,0,33,34.1,35.8

In [23]:
bacterialData = bacterialData.dropna()
bacterialData

,EventDate,SiteID,SiteName,site_latitude,site_longitude,plate_blank,plate_one,plate_two,plate_three,colony_avg,min_temp,max_temp
41180,2022-01-01 13:00:00,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,0.0,11,5,13,966,35.0,35.5
41181,2022-01-01 16:30:00,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,0.0,22,23,19,2133,34.6,35.8
41182,2022-01-03 09:40:00,6866,Lake Sovereign - CHD,34.1628,-84.5329,0.0,24,20,26,2333,35.0,35.0
41201,2022-01-05 10:42:00,954,Hollow Creek 2,33.3434,-81.8222,0.0,2,1,1,133,34.1,34.6
41203,2022-01-05 11:11:00,953,Hollow Creek 1,33.3345,-81.8534,0.0,1,2,0,100,34.1,34.6
...,...,...,...,...,...,...,...,...,...,...,...,...
46295,2022-12-19 14:45:00,7337,Ludie Creek at Simpsonwood Park,33.9827,-84.2436,0.0,1,1,0,66,34.9,35.2
46296,2022-12-19 14:53:00,2033,Peachtree Hills Park,33.8180,-84.3783,0.0,3,2,4,300,34.5,35.5
46298,2022-12-20 10:10:00,2368,Ball Mill Creek,33.9787,-84.3208,0.0,0,1,3,133,34.1,35.5
46304,2022-12-20 13:30:00,6564,Alapaha River at Naylor Park Beach,30.9254,-83.0385,0.0,1,1,1,100,34.0,35.0
46309,2022-12-21 12:10:00,6795,Allatoona Creek - Mason Bridge,34.0217,-84.7086,0.0,1,0,0,33,34.1,35.8

In [24]:
bacterialData = bacterialData[bacterialData["plate_one"] != "TNTC"]
bacterialData = bacterialData[(bacterialData["plate_two"] != "TNTC") & (bacterialData["plate_two"] != " ")]
bacterialData = bacterialData[bacterialData["plate_three"] != "TNTC"]

In [25]:
bacterialData["plate_one"] = bacterialData["plate_one"].astype(float)
bacterialData["plate_two"] = bacterialData["plate_two"].astype(float)
bacterialData["plate_three"] = bacterialData["plate_three"].astype(float)
bacterialData["colony_avg"] = bacterialData["colony_avg"].astype(float)

In [26]:
bacterialData["plate_one"] = bacterialData["plate_one"] * 100
bacterialData["plate_two"] = bacterialData["plate_two"] * 100
bacterialData["plate_three"] = bacterialData["plate_three"] * 100

In [27]:
bacterialData

,EventDate,SiteID,SiteName,site_latitude,site_longitude,plate_blank,plate_one,plate_two,plate_three,colony_avg,min_temp,max_temp
41180,2022-01-01 13:00:00,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,0.0,1100.0,500.0,1300.0,966.0,35.0,35.5
41181,2022-01-01 16:30:00,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,0.0,2200.0,2300.0,1900.0,2133.0,34.6,35.8
41182,2022-01-03 09:40:00,6866,Lake Sovereign - CHD,34.1628,-84.5329,0.0,2400.0,2000.0,2600.0,2333.0,35.0,35.0
41201,2022-01-05 10:42:00,954,Hollow Creek 2,33.3434,-81.8222,0.0,200.0,100.0,100.0,133.0,34.1,34.6
41203,2022-01-05 11:11:00,953,Hollow Creek 1,33.3345,-81.8534,0.0,100.0,200.0,0.0,100.0,34.1,34.6
...,...,...,...,...,...,...,...,...,...,...,...,...
46295,2022-12-19 14:45:00,7337,Ludie Creek at Simpsonwood Park,33.9827,-84.2436,0.0,100.0,100.0,0.0,66.0,34.9,35.2
46296,2022-12-19 14:53:00,2033,Peachtree Hills Park,33.8180,-84.3783,0.0,300.0,200.0,400.0,300.0,34.5,35.5
46298,2022-12-20 10:10:00,2368,Ball Mill Creek,33.9787,-84.3208,0.0,0.0,100.0,300.0,133.0,34.1,35.5
46304,2022-12-20 13:30:00,6564,Alapaha River at Naylor Park Beach,30.9254,-83.0385,0.0,100.0,100.0,100.0,100.0,34.0,35.0
46309,2022-12-21 12:10:00,6795,Allatoona Creek - Mason Bridge,34.0217,-84.7086,0.0,100.0,0.0,0.0,33.0,34.1,35.8

In [32]:

bacterialData["E Coli Colony Average Threat Level"] = pd.cut(bacterialData['colony_avg'], 
                        bins=[-1, 100, 235, 410,max(bacterialData['colony_avg'])],  # Define numeric ranges
                        labels=['Rarely Unsafe', 'Tends to be Unsafe','Sometimes Unsafe','Often Unsafe'])

In [33]:
import numpy as np

bacterialDataSites = bacterialData.groupby("SiteName").agg({
    "SiteID": "min",
    "EventDate": "mean",
    "colony_avg": lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan,
    "E Coli Colony Average Threat Level": lambda x: x.mode().iloc[0] if not x.mode().empty else np.nan,
    "site_latitude": "min",
    "site_longitude": "min"
}).reset_index()

In [34]:
bacterialDataSites

,SiteName,SiteID,EventDate,colony_avg,E Coli Colony Average Threat Level,site_latitude,site_longitude
0,Alapaha River - SR 203,7085,2022-05-09 16:12:30.000000000,133.0,Tends to be Unsafe,31.3756,-82.2887
1,Alapaha River at Naylor Park Beach,6564,2022-09-26 13:48:20.000000000,0.0,Rarely Unsafe,30.9254,-83.0385
2,Alapaha River at State Road 32 near Irwinville...,7055,2022-06-06 10:50:00.000000000,0.0,Rarely Unsafe,31.6312,-83.4178
3,"Alapaha River at State Road 35 near Tifton, GA",7094,2022-06-08 09:35:00.000000000,133.0,Tends to be Unsafe,31.5327,-83.3989
4,Alapahoochee Riv. at Antioch Rd/J'frank,7053,2022-03-30 15:40:00.000000000,33.0,Rarely Unsafe,30.6733,-83.1049
...,...,...,...,...,...,...,...
407,sherwood creek,7208,2022-04-17 11:53:04.615384576,66.0,Tends to be Unsafe,34.1078,-83.8994
408,tributary of Little Suwanne Creek,7348,2022-08-18 12:55:00.000000000,133.0,Tends to be Unsafe,34.0347,-84.0074
409,tributary to Canton Creek,2473,2022-07-08 22:57:20.000000000,33.0,Tends to be Unsafe,34.2321,-84.4906
410,unnamed tributary to Etowah River,2937,2022-08-26 07:32:24.000000000,0.0,Rarely Unsafe,34.2412,-84.4902
411,up stream Trib of Peachtree Creek,6932,2022-06-13 03:24:45.000000000,266.0,Often Unsafe,33.8055,-84.4172

In [35]:
bacterialDataSites.to_csv("/Users/keerthyrangan/Downloads/bacterialDataSitesCleaned.csv")

In [16]:
bacterialData = bacterialData.rename(columns={"plate_one": "1st Sample E Coli Colony Count","plate_two":"2nd Sample E Coli Colony Count",
                              "plate_three":"3rd Sample E Coli Colony Count",
                              "colony_avg":"E Coli Colony Average"})
bacterialData = bacterialData.drop(["plate_blank","min_temp","max_temp"],axis=1)
bacterialData

,EventDate,SiteID,SiteName,site_latitude,site_longitude,1st Sample E Coli Colony Count,2nd Sample E Coli Colony Count,3rd Sample E Coli Colony Count,E Coli Colony Average,1st Single Sample E Coli Threat Level,2nd Single Sample E Coli Threat Level,3rd Single Sample E Coli Threat Level,E Coli Colony Average Threat Level
41180,2022-01-01 13:00:00,7342,Cobbs Creek at Alverado Way,33.7484,-84.2546,1100.0,500.0,1300.0,966.0,High Risk for Waterborne Illness,High Risk for Waterborne Illness,High Risk for Waterborne Illness,Tends to be UnsafeOften Unsafe
41181,2022-01-01 16:30:00,869,Detention pond on tributary of Rubes Creek,34.0561,-84.4971,2200.0,2300.0,1900.0,2133.0,High Risk for Waterborne Illness,High Risk for Waterborne Illness,High Risk for Waterborne Illness,Tends to be UnsafeOften Unsafe
41182,2022-01-03 09:40:00,6866,Lake Sovereign - CHD,34.1628,-84.5329,2400.0,2000.0,2600.0,2333.0,High Risk for Waterborne Illness,High Risk for Waterborne Illness,High Risk for Waterborne Illness,Tends to be UnsafeOften Unsafe
41201,2022-01-05 10:42:00,954,Hollow Creek 2,33.3434,-81.8222,200.0,100.0,100.0,133.0,Still in Acceptable Threshold,Water Very Clean,Water Very Clean,Sometimes Unsafe
41203,2022-01-05 11:11:00,953,Hollow Creek 1,33.3345,-81.8534,100.0,200.0,0.0,100.0,Water Very Clean,Still in Acceptable Threshold,Water Very Clean,Rarely Unsafe
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46295,2022-12-19 14:45:00,7337,Ludie Creek at Simpsonwood Park,33.9827,-84.2436,100.0,100.0,0.0,66.0,Water Very Clean,Water Very Clean,Water Very Clean,Rarely Unsafe
46296,2022-12-19 14:53:00,2033,Peachtree Hills Park,33.8180,-84.3783,300.0,200.0,400.0,300.0,High Risk for Waterborne Illness,Still in Acceptable Threshold,High Risk for Waterborne Illness,Sometimes Unsafe
46298,2022-12-20 10:10:00,2368,Ball Mill Creek,33.9787,-84.3208,0.0,100.0,300.0,133.0,Water Very Clean,Water Very Clean,High Risk for Waterborne Illness,Sometimes Unsafe
46304,2022-12-20 13:30:00,6564,Alapaha River at Naylor Park Beach,30.9254,-83.0385,100.0,100.0,100.0,100.0,Water Very Clean,Water Very Clean,Water Very Clean,Rarely Unsafe
46309,2022-12-21 12:10:00,6795,Allatoona Creek - Mason Bridge,34.0217,-84.7086,100.0,0.0,0.0,33.0,Water Very Clean,Water Very Clean,Water Very Clean,Rarely Unsafe

In [13]:
bacterialData.to_csv("/Users/keerthyrangan/Downloads/bacterialDataCleaned.csv")